//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 07:12:59 PM BST 
//


package eventhandler.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the arrowhead.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: arrowhead.generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Registered }
     * 
     */
    public Registered createRegistered() {
        return new Registered();
    }

    /**
     * Create an instance of {@link Consumer }
     * 
     */
    public Consumer createConsumerType() {
        return new Consumer();
    }

    /**
     * Create an instance of {@link Producer }
     * 
     */
    public Producer createProducerType() {
        return new Producer();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMeta() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilterType() {
        return new Filter();
    }

}
